# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://sandipan.ml
baseurl: 
title: Sandipan Roy
author: Sandipan Roy
description: Personal Blog and Resume
avatar: nemo.png
email: sandipan@parrotsec.org
github: bytehackr # username
twitter: bytehackr
linkedin: bytehackr
# stackoverflow: username   #e.g: #users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: #username
google_analytics: UA-149016799-2



# needed for travis-ci build
exclude: [vendor]
